# Site settings
title: "/* mhcerri's notes */"
email: 
description: > # this means to ignore newlines until "baseurl:"
  Random notes about technical stuff that I would probably forget
  next week :-)
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://mhcerri.github.io" # the base hostname & protocol for your site
twitter_username: 
github_username:  mhcerri

# Build settings
markdown: redcarpet
